schedules:
  - cron: "0 7 * * Mon-Fri"
    displayName: M-F 7:00 AM (UTC) daily build
  - cron: "0 9 * * Sun"
    displayName: Sunday 9:00 AM (UTC) weekly latest version build
    branches:
      include:
        - /releases/lastversion
    always: true
jobs:
  - job: Test
    strategy:
      maxParallel: 2
      matrix:
        US_IE:
          Location: US
          Browser: IE
        US_Chrome:
          Location: US
          Browser: Chrome
        Europe_Chrome:
          Location: Europe
          Browser: Chrome
    steps:
      - script: echo $(Location) # echos A or B depending on which leg is running
